// Generated by `make changelog` from CHANGELOG.md — do not edit by hand.
// Re-run `make changelog` (or any `make build*` target) after editing the source.

enum ChangelogData {
    /// The full CHANGELOG.md, baked in at build time. Rendered as Markdown by
    /// the in-app changelog page.
    static let markdown = #"""
# Changelog

All notable changes to Cling are recorded here.
The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and the project follows [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- **Changelog, in the app.** This page — the full release history, baked into the
  build from `CHANGELOG.md` and reachable from Settings → Changelog. Each version
  is an expandable card; the latest opens first. (`make changelog`,
  `ChangelogData`, `ChangelogView`)

### Changed
- **The board sorts by what's happening soonest.** Pins are ordered by their
  scheduled start instead of when you added them, so a match kicking off in an
  hour sits above a fight four days out, and ambient pins (timers, parking, notes)
  stay near the top. (`Pin.scheduledStart`, `AppModel.activePins`)
- **Cleaner cards.** Dropped the vertical accent bar down the left edge of every
  pin card — the card's own tint already carries the colour.

### Fixed
- **Suspended matches now show "Susp." instead of a frozen minute.** A match
  stopped mid-play (crowd trouble, weather, floodlight failure) kept reporting as
  live, so the island and card froze on a stale "45'". Cling now reads the feed's
  status name, shows a "Susp." label with an amber dot, and switches back to live
  automatically when play resumes. (`MatchStatus.suspended`, `MatchFeed.mapStatus`,
  server `espn.ts` `matchStatus`)
- **Live Activity no longer renders empty when several pins are live.** iOS
  silently drops a Live Activity whose content-state exceeds ~4 KB, which left the
  lock-screen card and Dynamic Island blank while the app showed the full roster.
  The roster now trims itself to fit the budget — keeping the most relevant pins —
  on both the in-app update and the closed-app push path.
  (`ActivityPushContract.fitToBudget`)

### Design
- **App icon mark.** The push-pin glyph is now molded into the glass disc with a
  vivid violet→indigo gradient, an engraved shadow, and a glossy sheen — matching
  the family treatment (Clink's keycap "C", Aware's shield). (`make icon`)

## [1.0.0] - 2026-06-22

The first Cling: pin what you're watching to your Dynamic Island and lock screen,
and keep it there.

### Added
- **One activity, every pin.** Cling runs a single Live Activity that carries your
  whole board as a roster. One pin shows richly — its own lock-screen card and
  Dynamic Island regions — and when several are live they collapse into a compact
  stacked list, with the lead pin driving the compact island. iOS only ever shows
  one activity, so this is the honest way to keep them all glanceable.
- **Eight pin types.**
  - **Timer** — a labelled countdown that ticks client-side (no battery spent on
    updates), drawn as plain numerals, a draining ring, a bar, or a filled gauge.
  - **Parking** — where you left the car, with a note, a saved spot, and a
    one-tap **Directions** action back to it.
  - **Note** — a scrap of text or a shared web link, pinned for quick reference.
  - **Match** — a live football scoreline with flags, the minute, and optional
    play-by-play commentary, driven by a live feed.
  - **Fight** — a UFC/MMA bout with the two fighters, the round and clock, and the
    result when it lands.
  - **Game** — NBA / NFL / NHL / MLB scores with period and clock, all sharing one
    renderer.
  - **Ticker** — a stock or crypto quote with the day's move and a sparkline.
  - **Decor** — a purely decorative glyph pin, for marking a moment.
- **Live sports that update while the app is closed.** Pinned matches, fights,
  games and tickers are kept current by a Cloudflare Worker that polls ESPN (and a
  quote API) and pushes fresh scores to the activity over APNs — so the lock
  screen stays live without Cling running. Goals, full-time and fight results
  arrive as banner alerts; routine clock ticks stay quiet to spare the update
  budget.
- **Push-to-start.** A pinned sport can launch its Live Activity from a closed app
  the moment it goes live, via a registered push-to-start token.
- **Quick add.** A single composer for every pin type, with type-specific fields
  and sensible defaults — start typing and pin it.
- **Share extension.** Send a web page or selected text to Cling from any app to
  pin it as a note, source link kept.
- **Home-screen widget.** A glanceable widget that reads the same pinned board the
  app shows.
- **A look you set once.** A house style — surface (glass / solid / outline),
  density, type design and card edge — applied across every pin and the Dynamic
  Island, with a per-type accent colour (flat or gradient) and glyph. Change the
  feel once and the whole board re-dresses.
- **Honest expiry.** iOS unpins every Live Activity after 8 hours. Cling names the
  ceiling on each card ("Pinned until …"), nudges you with a renewal reminder
  shortly before, and — when a pin does fall off — marks it stale and re-armable
  rather than pretending it's still live.
- **Directions your way.** Parking directions open in Apple Maps, Google Maps or
  Waze, your pick.

[Unreleased]: https://github.com/anti-ltd/cling
[1.0.0]: https://github.com/anti-ltd/cling/releases/tag/v1.0.0
"""#
}
