/**
 The in-app changelog: the build-time-baked `CHANGELOG.md` (`ChangelogData.markdown`,
 generated by `make changelog`) rendered as one expandable card per version. The
 latest version (first in the file) starts expanded; older ones start collapsed.
 Reached from Settings → Changelog.
 */
import SwiftUI
import iUXiOS

struct ChangelogView: View {
    @Environment(AppModel.self) private var model

    var body: some View {
        ScrollView {
            VStack(spacing: 12) {
                ForEach(versions) { v in
                    ChangelogCard(version: v, isLatest: v.id == 0)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(UX.screenPadding)
        }
        .background {
            AmbientBackdrop(tint: model.settings.appAccent.color)
                .ignoresSafeArea()
        }
        .navigationTitle("Changelog")
        .navigationBarTitleDisplayMode(.inline)
    }

    /// Split the markdown into version sections at each `## [x.y.z]` heading. The
    /// top "# Changelog" + intro paragraph before the first one is dropped.
    private var versions: [ChangelogVersion] {
        var out: [ChangelogVersion] = []
        var title: String? = nil
        var body: [String] = []
        func flush() {
            if let title { out.append(.init(id: out.count, title: title, bodyLines: body)) }
            body = []
        }
        for raw in ChangelogData.markdown.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(raw)
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("## ") {
                flush()
                title = String(trimmed.dropFirst(3))
                    .replacingOccurrences(of: "[", with: "")
                    .replacingOccurrences(of: "]", with: "")
            } else if title != nil {
                // Skip the link-reference footer ([Unreleased]: https://…).
                if trimmed.hasPrefix("[") && trimmed.contains("]: ") { continue }
                body.append(line)
            }
        }
        flush()
        return out
    }
}

/// One parsed version section: its header (`## [1.0.0] - date`) plus the body
/// lines up to the next version header.
private struct ChangelogVersion: Identifiable {
    let id: Int
    /// Display title with the markdown brackets stripped, e.g. "1.0.0 - 2026-06-22".
    let title: String
    let bodyLines: [String]
}

/// A single expandable version card: tappable header with version + date and a
/// chevron, animated body reveal. CHANGELOG.md hard-wraps its bullets across
/// several source lines, so the parser *reflows* continuation lines back into
/// their bullet/paragraph before rendering; `AttributedString(markdown:)` styles
/// inline **bold** / `code` / links.
private struct ChangelogCard: View {
    @Environment(\.cardCornerRadius) private var cardCornerRadius
    @Environment(\.cardTint) private var cardTint
    let version: ChangelogVersion
    let isLatest: Bool
    @State private var expanded: Bool

    init(version: ChangelogVersion, isLatest: Bool) {
        self.version = version
        self.isLatest = isLatest
        _expanded = State(initialValue: isLatest)
    }

    private enum Block {
        case section(String)              // "Added" / "Fixed" / …
        case bullet(AttributedString)
        case paragraph(AttributedString)
    }

    /// Reflow the hard-wrapped markdown body into logical blocks. A line that is
    /// neither blank, a `###` section, nor a new `- ` bullet is a wrapped
    /// continuation and gets appended to whatever block is open.
    private var blocks: [Block] {
        var out: [Block] = []
        var buf: String? = nil
        var bufIsBullet = false
        func flush() {
            guard let t = buf else { return }
            out.append(bufIsBullet ? .bullet(inline(t)) : .paragraph(inline(t)))
            buf = nil
        }
        for line in version.bodyLines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { flush(); continue }
            if trimmed.hasPrefix("### ") {
                flush(); out.append(.section(String(trimmed.dropFirst(4)))); continue
            }
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                flush(); buf = String(trimmed.dropFirst(2)); bufIsBullet = true; continue
            }
            if buf != nil { buf! += " " + trimmed }
            else { buf = trimmed; bufIsBullet = false }
        }
        flush()
        return out
    }

    /// Inline-only markdown → AttributedString. `.inlineOnlyPreservingWhitespace`
    /// keeps a line's text intact while still styling bold/code/links.
    private func inline(_ s: String) -> AttributedString {
        (try? AttributedString(
            markdown: s,
            options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
        )) ?? AttributedString(s)
    }

    /// "1.0.0 - 2026-06-22" → ("1.0.0", "2026-06-22"). Tolerates both an em dash
    /// and a hyphen separator.
    private var versionParts: (number: String, date: String?) {
        for sep in [" — ", " - "] {
            let parts = version.title.components(separatedBy: sep)
            if parts.count > 1 { return (parts[0], parts[1]) }
        }
        return (version.title, nil)
    }

    /// Section accent — a subtle semantic colour per Keep-a-Changelog group.
    private func sectionColor(_ name: String) -> Color {
        switch name.lowercased() {
        case "added":            return .green
        case "changed":          return .blue
        case "fixed":            return .orange
        case "design":           return .pink
        case let s where s.hasPrefix("security"): return .purple
        case "removed", "deprecated": return .red
        default:                 return .secondary
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            if expanded {
                Divider().opacity(0.5).padding(.horizontal, 14)
                body(content)
            }
        }
        .background {
            RoundedRectangle(cornerRadius: cardCornerRadius, style: .continuous)
                .fill(cardTint ?? Color(.secondarySystemBackground))
        }
        .overlay {
            RoundedRectangle(cornerRadius: cardCornerRadius, style: .continuous)
                .strokeBorder(
                    isLatest ? AnyShapeStyle(.tint.opacity(0.45)) : AnyShapeStyle(.primary.opacity(UX.Glass.outlineOpacity)),
                    lineWidth: isLatest ? 1 : UX.Glass.outlineWidth
                )
        }
        .clipShape(RoundedRectangle(cornerRadius: cardCornerRadius, style: .continuous))
    }

    private var header: some View {
        Button {
            withAnimation(.snappy(duration: 0.28)) { expanded.toggle() }
        } label: {
            HStack(spacing: 8) {
                Text(versionParts.number)
                    .font(.headline)
                    .foregroundStyle(.primary)
                if let date = versionParts.date {
                    Text(date)
                        .font(.caption.weight(.medium))
                        .foregroundStyle(.secondary)
                }
                if isLatest {
                    Text("LATEST")
                        .font(.caption2.weight(.bold))
                        .tracking(0.5)
                        .foregroundStyle(.tint)
                        .padding(.horizontal, 6).padding(.vertical, 2)
                        .background(RoundedRectangle(cornerRadius: min(cardCornerRadius, 10), style: .continuous)
                            .fill(.tint.opacity(0.15)))
                }
                Spacer()
                Image(systemName: "chevron.down")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(.secondary)
                    .rotationEffect(.degrees(expanded ? 0 : -90))
            }
            .padding(14)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    @ViewBuilder private var content: some View {
        ForEach(Array(blocks.enumerated()), id: \.offset) { _, block in
            switch block {
            case .section(let s):
                HStack(spacing: 6) {
                    Circle().fill(sectionColor(s)).frame(width: 6, height: 6)
                    Text(s.uppercased())
                        .font(.caption2.weight(.bold))
                        .tracking(0.8)
                        .foregroundStyle(sectionColor(s))
                }
                .padding(.top, 10)
            case .bullet(let a):
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    Circle().fill(.tertiary).frame(width: 4, height: 4)
                        .padding(.top, 6)
                    Text(a)
                        .font(.callout)
                        .foregroundStyle(.primary.opacity(0.85))
                        .fixedSize(horizontal: false, vertical: true)
                }
            case .paragraph(let a):
                Text(a)
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    private func body(_ inner: some View) -> some View {
        VStack(alignment: .leading, spacing: 7) {
            inner
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(14)
        .transition(.opacity)
    }
}
